// Regenerate reports/index.js from reports/*.json, ATOMICALLY — the file:// counterpart of
// serve.mjs's /api/reports. The board loads it as window.__JIRA_PR_REPORTS__ so PR Readiness
// Reports open with no server at all. Reports are a few KB each, so inlining all of them is fine.
//
//   node sync-reports.mjs <intern-dir>
//
// Also carries `generating` (keys some process is building right now, from reports/.status.json,
// dead PIDs dropped) so the board can show "report in progress" in file:// mode too.
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'

const dir = process.argv[2]
if (!dir) {
  process.stderr.write('usage: node sync-reports.mjs <intern-dir>\n')
  process.exit(2)
}
const reportsDir = join(dir, 'reports')
mkdirSync(reportsDir, { recursive: true })
const dst = join(reportsDir, 'index.js')
const tmp = join(reportsDir, '.index.js.swap')

const reports = {}
for (const name of readdirSync(reportsDir)) {
  if (!name.endsWith('.json') || name.startsWith('.')) continue
  try {
    const r = JSON.parse(readFileSync(join(reportsDir, name), 'utf8'))
    if (r && typeof r.key === 'string') reports[r.key] = r
  } catch (e) {
    process.stderr.write(`sync-reports: skipping unreadable ${name}: ${e.message}\n`)
  }
}

// Live "generating" set — same rule as serve.mjs: a registered PID that no longer exists is stale.
const generating = []
const statusPath = join(reportsDir, '.status.json')
if (existsSync(statusPath)) {
  try {
    const st = JSON.parse(readFileSync(statusPath, 'utf8'))
    for (const [key, v] of Object.entries(st?.generating || {})) {
      const pid = Number(v?.pid)
      if (!Number.isInteger(pid) || pid <= 0) continue
      try {
        process.kill(pid, 0)
        generating.push(key)
      } catch (e) {
        if (e.code !== 'ESRCH') generating.push(key)
      }
    }
  } catch {}
}

try {
  const js =
    '// AUTO-GENERATED by sync-reports.mjs from reports/*.json. Do not edit by hand.\n' +
    'window.__JIRA_PR_REPORTS__ = ' +
    JSON.stringify({ reports, generating, count: Object.keys(reports).length }, null, 2) +
    ';\n'
  writeFileSync(tmp, js)
  renameSync(tmp, dst)
  process.stdout.write(`sync-reports: ${Object.keys(reports).length} report(s), ${generating.length} generating\n`)
} catch (e) {
  try {
    rmSync(tmp, { force: true })
  } catch {}
  process.stderr.write(`sync-reports: failed: ${e.message}\n`)
  process.exit(1)
}
