import type { JiraData } from './types'

// ─────────────────────────────────────────────────────────────────────────
// SAMPLE DATA — used ONLY in `npm run dev` so the UI has something rich to
// render while designing. It is dead-code-eliminated from the production
// build (loadData guards it behind import.meta.env.DEV). The real board
// always reads window.__JIRA_DATA__ from jira-intern/data.js.
// ─────────────────────────────────────────────────────────────────────────
export const fixture: JiraData = {
  generatedAt: '2026-06-30T15:50:00Z',
  user: { name: 'Alex Doe', accountId: 'DEV001', jiraBase: 'https://jira.example.com' },
  notes: ['SAMPLE preview data (npm run dev) — the built board shows your real tickets.'],
  tickets: [
    {
      key: 'RISK-190',
      title: 'Create agent-insight release',
      status: 'To Do',
      column: 'todo',
      type: 'Sub-task',
      priority: 'High',
      storyPoints: null,
      branch: 'feature/RISK-190_create_agent_insight_release',
      estDays: '2–3 days',
      pr: { state: 'none' },
      commentCount: 0,
      lastUpdate: '2026-06-30T15:00:00Z',
      created: '2026-06-26T09:00:00Z',
      done: false,
      url: 'https://jira.example.com/browse/RISK-190',
      sprint: 'Agent Trust Sprint 4 (future · 2026-06-28 → 2026-07-10)',
      reporter: 'Cox, Christopher',
      assignee: 'Alex Doe (DEV001)',
      labels: ['release', 'platform'],
      components: ['agent-insight'],
      description: '<p>Create the <b>agent-insight release within the platform</b>. This includes a <b>release stream</b> and a <b>release build pipeline</b> to build the release and add it to the provisioning service.</p><p>Repository: <code>PHIN/agent-insight</code>.</p>',
      aiSummary:
        '<p>Stand up a first production release for <b>agent-insight</b>: a release stream plus a build pipeline that publishes the artifact and registers it with the provisioning service. Not started yet — the pattern is well understood, so the main work is wiring, not design.</p>' +
        '<b>From linked docs</b><ul>' +
        '<li><a href="https://confluence.example.com/x/runbook">Platform release runbook</a> — new streams are added in <code>ReleaseStreams.groovy</code>; a stream needs an owner + target envs before provisioning will accept it.</li>' +
        '<li>Runbook step 4 requires a green build on <code>develop</code> before the stream is promoted.</li></ul>' +
        '<b>Related tickets</b><ul>' +
        '<li><a href="https://jira.example.com/browse/RISK-150">RISK-150</a> (Done) — bootstrapped the agent-trust pipeline; reuse its Jenkinsfile as the template.</li></ul>' +
        '<b>Code / PRs</b><ul><li>No PR yet. Model the change on the existing <code>kya-platform</code> stream entry in <code>PHIN/agent-insight</code>.</li></ul>' +
        '<b>Attachments &amp; links</b><ul><li>No attachments on the ticket.</li></ul>',
      aiSummaryAt: '2026-06-30T15:05:00Z',
      acceptanceCriteria: ['Release stream created', 'Build pipeline produces a release', 'Release registered with provisioning service'],
      confluence: [{ title: 'Platform release runbook', url: 'https://confluence.example.com/x/runbook', excerpt: 'Steps for adding a new release stream.' }],
      proposedSolution: '<ul><li>Add an <code>agent-insight</code> entry to <code>ReleaseStreams.groovy</code> modeled on <code>kya-platform</code>.</li><li>Create the release build pipeline; register with the provisioning service.</li></ul>',
      effortEstimate: '<p><b>2–3 days</b> — mostly pipeline wiring + provisioning registration; low logic risk, follows an existing pattern.</p>',
      openQuestions: ['Which environments should the initial release target?', 'Any approval gate before adding to provisioning?'],
      sources: [{ title: 'Jira RISK-190', url: 'https://jira.example.com/browse/RISK-190' }],
      updateLog: [{ when: '2026-06-30', text: 'Assigned — initial brief' }],
    },
    {
      key: 'MATCH-4521',
      title: 'Cache warm-up for match scoring service',
      status: 'Dev in Progress',
      column: 'prog',
      type: 'Story',
      priority: 'Medium',
      storyPoints: 8,
      branch: 'feature/MATCH-4521_match_cache_warmup',
      estDays: '4 days',
      pr: { state: 'none' },
      commentCount: 2,
      lastUpdate: '2026-06-30T11:20:00Z',
      created: '2026-06-22T09:00:00Z',
      url: 'https://jira.example.com/browse/MATCH-4521',
      reporter: 'Ortega, Lucia',
      assignee: 'Alex Doe (DEV001)',
      labels: ['performance'],
      description: '<p>Warm the scoring cache on deploy to remove the cold-start latency spike on the first batch of the day.</p>',
      aiSummary:
        '<p>Eliminate the cold-start latency spike on the first scoring batch by warming the cache at service startup. The warm-up loop is implemented and metrics wiring is in progress; next step is to expose the <code>cache_warm_seconds</code> gauge and validate p99 &lt; 400ms in staging.</p>' +
        '<b>From linked docs</b><ul>' +
        '<li><a href="https://confluence.example.com/x/scoring-latency">Scoring latency budget</a> — first-batch p99 must stay under 400ms; cold cache was measured at ~1.2s.</li></ul>' +
        '<b>Code / PRs</b><ul>' +
        '<li>Branch <code>feature/MATCH-4521_match_cache_warmup</code>, no PR opened yet. Change touches <code>ScoringCacheLoader</code> and the startup hook in <code>example-match</code>.</li></ul>' +
        '<b>Attachments &amp; links</b><ul>' +
        '<li><a href="https://grafana.example.com/d/scoring">Grafana: scoring p99</a> — dashboard to confirm the spike is gone after deploy.</li></ul>',
      aiSummaryAt: '2026-06-30T11:25:00Z',
      acceptanceCriteria: ['p99 first-batch latency < 400ms', 'Warm-up runs on startup', 'Metric exposed'],
      updateLog: [{ when: '2026-06-30', text: 'Implemented warm-up loop; wiring metrics' }, { when: '2026-06-27', text: 'Assigned — initial brief' }],
    },
    {
      key: 'PROJ-6048',
      title: 'Remediate FA-JBOSS container vulnerabilities in STG',
      status: 'Ready4Review',
      column: 'rev',
      type: 'Security',
      priority: 'High',
      storyPoints: 5,
      branch: 'feature/PROJ-6048_jboss_container_vulnerabilities_stg',
      estDays: '1d + vendor wait',
      pr: { state: 'comments', url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/362', id: 362, approvals: 1, openComments: 2, sourceBranch: 'feature/PROJ-6048_jboss_container_vulnerabilities_stg', destinationBranch: 'develop' },
      branches: ['feature/PROJ-6048_jboss_container_vulnerabilities_stg', 'bugfix/PROJ-6048_openjdk_cve_mitigation'],
      prs: [
        { state: 'comments', id: 362, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/362', approvals: 1, openComments: 2, sourceBranch: 'feature/PROJ-6048_jboss_container_vulnerabilities_stg', destinationBranch: 'develop' },
        { state: 'declined', id: 351, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/351', approvals: 0, sourceBranch: 'bugfix/PROJ-6048_openjdk_cve_mitigation', destinationBranch: 'develop' },
      ],
      commentCount: 3,
      latestComment: '2026-06-29T12:46:12Z',
      lastUpdate: '2026-06-30T18:00:00Z',
      created: '2026-06-18T09:00:00Z',
      url: 'https://jira.example.com/browse/PROJ-6048',
      sprint: 'PROJ 89_2026 (active · 2026-06-24 → 2026-07-08)',
      reporter: 'Nookala, Srividya',
      assignee: 'Alex Doe (DEV001)',
      epic: { key: 'PROJ-5999', url: 'https://jira.example.com/browse/PROJ-5999', relation: 'epic' },
      labels: ['security', 'cve', 'out-of-sla'],
      components: ['example-jboss'],
      description: '<p>Remediate <b>FA-JBOSS container vulnerabilities</b>, likely needs a refresh with the latest image. All listed vulnerabilities are <b>Out of SLA</b>.</p>',
      acceptanceCriteria: ['FA images refreshed', 'Use the golden image', 'Coordinate with Prabhat (did ASPID)'],
      comments: [
        { author: 'Alex Doe', when: '2026-06-29T12:46:12Z', body: 'CVE status — <code>java-21-openjdk*</code> on RHEL 9: <b>CVE-2025-66293</b> &amp; <b>CVE-2026-25646</b> are <b>Affected</b>, no released fix.' },
        { author: 'Nookala, Srividya', when: '2026-06-26T08:10:00Z', body: 'Please prioritise — out of SLA.' },
      ],
      related: [{ key: 'PROJ-5999', url: 'https://jira.example.com/browse/PROJ-5999', summary: 'JBOSS hardening epic', status: 'In Progress', relation: 'epic (parent)' }],
      subtaskCount: 2,
      subtasks: [
        {
          key: 'PROJ-6049',
          title: 'Refresh FA-JBOSS base image to golden image',
          status: 'In Progress',
          column: 'prog',
          type: 'Sub-task',
          priority: 'High',
          parentKey: 'PROJ-6048',
          branch: 'feature/PROJ-6049_golden_image_refresh',
          pr: { state: 'none' },
          url: 'https://jira.example.com/browse/PROJ-6049',
          description: '<p>Bump the FA-JBOSS Dockerfile base to the latest golden image and rebuild.</p>',
          updateLog: [
            { when: '2026-06-30', text: 'Moved To Do → In Progress — 2026-06-30' },
            { when: '2026-06-26', text: 'Opened — 2026-06-26' },
          ],
        },
        {
          key: 'PROJ-6050',
          title: 'Redeploy & verify FA images in STG',
          status: 'To Do',
          column: 'todo',
          type: 'Sub-task',
          priority: 'Medium',
          parentKey: 'PROJ-6048',
          url: 'https://jira.example.com/browse/PROJ-6050',
          description: '<p>Deploy the refreshed images to STG and confirm the scanner is clean.</p>',
          updateLog: [{ when: '2026-06-26', text: 'Opened — 2026-06-26' }],
        },
      ],
      proposedSolution: '<p>Repo: <code>PIDCLIENTADM/example-jboss/</code>. Primarily a <b>base-image refresh to the golden image</b> once a fixed OpenJDK is available; rebuild &amp; redeploy to STG.</p>',
      effortEstimate: '<p><b>~1 day</b> active work then <b>vendor wait</b> for the two unfixed CVEs.</p>',
      openQuestions: ['Is a golden image with patched OpenJDK available yet?', 'Which exact FA images are in scope for STG?'],
      sources: [{ title: 'Jira PROJ-6048', url: 'https://jira.example.com/browse/PROJ-6048' }, { title: 'Epic PROJ-5999', url: 'https://jira.example.com/browse/PROJ-5999' }],
      updateLog: [
        { when: '2026-06-30', text: 'Moved In Progress → In Review — 2026-06-30 (PR #362 opened)' },
        { when: '2026-06-24', text: 'Moved To Do → In Progress — 2026-06-24' },
        { when: '2026-06-18', text: 'Opened — 2026-06-18' },
      ],
    },
    {
      key: 'RULES-2207',
      title: 'Validate new fraud rule pack in QA',
      status: 'QA',
      column: 'qa',
      type: 'Task',
      priority: 'Medium',
      storyPoints: 3,
      branch: 'feature/RULES-2207_fraud_rule_pack',
      estDays: '2 days',
      pr: { state: 'approved', url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-rules/pull-requests/88', id: 88, approvals: 2, openComments: 0 },
      commentCount: 1,
      lastUpdate: '2026-06-29T16:40:00Z',
      created: '2026-06-15T09:00:00Z',
      url: 'https://jira.example.com/browse/RULES-2207',
      reporter: 'Singh, Arun',
      assignee: 'Alex Doe (DEV001)',
      labels: ['fraud', 'rules'],
      description: '<p>Hand off the new rule pack to QA and support verification.</p>',
      acceptanceCriteria: ['QA sign-off', 'No regressions in baseline suite'],
      updateLog: [{ when: '2026-06-29', text: 'PR approved; handed to QA' }],
    },
    {
      key: 'PAY-991',
      title: 'Add audit logging to settlement endpoint',
      status: 'Done',
      column: 'done',
      type: 'Story',
      priority: 'Low',
      storyPoints: 5,
      branch: 'feature/PAY-991_audit_logging',
      estDays: '3 days',
      pr: { state: 'approved', url: 'https://bitbucket.example.com/projects/FARS/repos/example-pay/pull-requests/410', id: 410, approvals: 2, openComments: 0 },
      commentCount: 0,
      lastUpdate: '2026-06-28T10:00:00Z',
      created: '2026-06-10T09:00:00Z',
      done: true,
      url: 'https://jira.example.com/browse/PAY-991',
      reporter: 'Kim, Dana',
      assignee: 'Alex Doe (DEV001)',
      labels: ['audit'],
      description: '<p>Structured audit logging on the settlement endpoint for compliance.</p>',
      updateLog: [{ when: '2026-06-28', text: 'Marked DONE (status: Done)' }],
    },
    {
      key: 'LEND-77',
      title: 'Investigate intermittent timeout on batch importer',
      status: 'Blocked',
      column: 'hold',
      type: 'Bug',
      priority: 'Critical',
      storyPoints: 2,
      branch: 'bugfix/LEND-77_batch_timeout',
      estDays: 'blocked',
      pr: { state: 'changes', url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-rules/pull-requests/91', id: 91, approvals: 0, openComments: 4 },
      commentCount: 5,
      latestComment: '2026-06-30T09:15:00Z',
      lastUpdate: '2026-06-30T09:15:00Z',
      created: '2026-06-20T09:00:00Z',
      onHold: true,
      url: 'https://jira.example.com/browse/LEND-77',
      reporter: 'Patel, Nisha',
      assignee: 'Alex Doe (DEV001)',
      labels: ['bug', 'blocked'],
      description: '<p>Importer intermittently times out under load. <b>Blocked</b> pending infra capacity data from the platform team.</p>',
      openQuestions: ['When will infra provide the capacity metrics?'],
      updateLog: [{ when: '2026-06-30', text: 'Blocked — waiting on infra capacity data' }, { when: '2026-06-24', text: 'Reproduced under load' }],
    },
  ],
  completed: [
    {
      key: 'PROJ-5980',
      title: 'Patch log4j in ASPID containers',
      type: 'Security',
      priority: 'High',
      project: 'PROJ',
      status: 'Done',
      created: '2026-05-12',
      resolved: '2026-05-28',
      storyPoints: 3,
      branch: 'bugfix/PROJ-5980_log4j_aspid',
      pr: { state: 'merged', id: 351, merged: true, mergedAt: '2026-05-27', approvals: 2, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/351' },
      reporter: 'Nookala, Srividya',
      assignee: 'Alex Doe (DEV001)',
      labels: ['security', 'log4j'],
      description: '<p>Bump log4j to a patched version across all ASPID container images and redeploy.</p>',
      acceptanceCriteria: ['All images on patched log4j', 'No scanner findings'],
      updateLog: [
        { when: '2026-05-28', text: 'Marked DONE — 2026-05-28' },
        { when: '2026-05-27', text: 'Moved In Review → Done — 2026-05-27 (PR #351 merged)' },
        { when: '2026-05-20', text: 'Moved In Progress → In Review — 2026-05-20' },
        { when: '2026-05-12', text: 'Opened — 2026-05-12' },
      ],
      sources: [{ title: 'Jira PROJ-5980', url: 'https://jira.example.com/browse/PROJ-5980' }],
      url: 'https://jira.example.com/browse/PROJ-5980',
      branches: ['bugfix/PROJ-5980_log4j_aspid', 'bugfix/PROJ-5980_first_attempt'],
      prs: [
        { state: 'merged', id: 351, merged: true, mergedAt: '2026-05-27', approvals: 2, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/351', sourceBranch: 'bugfix/PROJ-5980_log4j_aspid', destinationBranch: 'develop' },
        { state: 'declined', id: 349, approvals: 0, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-app/pull-requests/349', sourceBranch: 'bugfix/PROJ-5980_first_attempt', destinationBranch: 'develop' },
      ],
      subtaskCount: 2,
      subtasks: [
        { key: 'PROJ-5981', title: 'Patch log4j in scoring container', status: 'Done', column: 'done', type: 'Sub-task', priority: 'High', parentKey: 'PROJ-5980', done: true, resolved: '2026-05-26', pr: { state: 'merged', id: 352, merged: true }, url: 'https://jira.example.com/browse/PROJ-5981' },
        { key: 'PROJ-5982', title: 'Re-scan ASPID images', status: 'Done', column: 'done', type: 'Sub-task', priority: 'Medium', parentKey: 'PROJ-5980', done: true, resolved: '2026-05-28', url: 'https://jira.example.com/browse/PROJ-5982' },
      ],
    },
    { key: 'PROJ-5982', title: 'Re-scan ASPID images (sub-task — should NOT appear in archive)', type: 'Sub-task', priority: 'Medium', project: 'PROJ', status: 'Done', resolved: '2026-05-28', url: 'https://jira.example.com/browse/PROJ-5982' },
    { key: 'MATCH-4490', title: 'Refactor scoring config loader', type: 'Story', priority: 'Medium', project: 'MATCH', status: 'Done', created: '2026-05-02', resolved: '2026-05-19', storyPoints: 5, branch: 'feature/MATCH-4490_config_loader', pr: { state: 'merged', id: 120, merged: true, approvals: 1, url: 'https://bitbucket.example.com/projects/PM/repos/example-match/pull-requests/120' }, url: 'https://jira.example.com/browse/MATCH-4490' },
    { key: 'RULES-2188', title: 'Fix NPE in rule evaluator', type: 'Bug', priority: 'High', project: 'RULES', status: 'Closed', created: '2026-04-21', resolved: '2026-04-30', storyPoints: 2, branch: 'bugfix/RULES-2188_npe_rule_eval', pr: { state: 'merged', id: 77, merged: true, url: 'https://bitbucket.example.com/projects/SAMPLE/repos/example-rules/pull-requests/77' }, url: 'https://jira.example.com/browse/RULES-2188' },
    { key: 'PAY-975', title: 'Settlement reconciliation report', type: 'Story', priority: 'Medium', project: 'PAY', status: 'Done', created: '2026-03-20', resolved: '2026-04-12', storyPoints: 8, branch: 'feature/PAY-975_recon_report', pr: { state: 'merged', id: 402, merged: true }, url: 'https://jira.example.com/browse/PAY-975' },
    { key: 'PROJ-5901', title: 'Upgrade base image to RHEL 9', type: 'Task', priority: 'Medium', project: 'PROJ', status: 'Done', created: '2026-03-01', resolved: '2026-03-22', storyPoints: 5, branch: 'feature/PROJ-5901_rhel9', pr: { state: 'merged', merged: true }, url: 'https://jira.example.com/browse/PROJ-5901' },
    { key: 'MATCH-4401', title: 'Add p99 latency dashboard', type: 'Task', priority: 'Low', project: 'MATCH', status: 'Done', created: '2026-02-01', resolved: '2026-02-15', storyPoints: 3, branch: 'feature/MATCH-4401_p99_dashboard', url: 'https://jira.example.com/browse/MATCH-4401' },
    { key: 'RISK-150', title: 'Bootstrap agent-trust pipeline', type: 'Story', priority: 'High', project: 'RISK', status: 'Done', created: '2025-11-18', resolved: '2025-12-09', storyPoints: 8, branch: 'feature/RISK-150_bootstrap', pr: { state: 'merged', id: 12, merged: true }, url: 'https://jira.example.com/browse/RISK-150' },
    { key: 'RULES-2099', title: 'Migrate rule store to v2 schema', type: 'Story', priority: 'High', project: 'RULES', status: 'Done', created: '2025-10-06', resolved: '2025-11-02', storyPoints: 13, branch: 'feature/RULES-2099_rule_store_v2', pr: { state: 'merged', id: 60, merged: true }, url: 'https://jira.example.com/browse/RULES-2099' },
  ],
}
